services:
  dev:
    image: node-dev:22              # 共用 image
    container_name: obsidian-note-protection-dev
    volumes:
      - .:/obsidian-note-protection
      - /obsidian-note-protection/node_modules
    working_dir: /obsidian-note-protection
    stdin_open: true
    tty: true
    command: /bin/sh
